# Generated by Django 5.1.3 on 2024-12-17 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome_curso', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriarCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_certificado', models.UUIDField(default=uuid.uuid1, editable=False, unique=True)),
                ('criacao_certificado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
