# Generated by Django 5.1.3 on 2024-12-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
